In [17]:
import ROOT
import uproot
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

#name = "130pp"
#name = "130CS"
#name = "40pp"
#name = "40CS"
#name = "130AA"
name = "40AA"

### Define input files
fileName    = "/data/alice/wesselr/07-09-2021_58MB_Pt120_tune14_10k_SD/JetToyHIResultSoftDrop.root"
events      = uproot.open(fileName)["jetTreeSig"]
variables   = events.keys()

eigen   = np.zeros((len(variables),len(variables),2))
vector  = np.zeros((len(variables),len(variables),4))

### Function calculating PCA
def calculatePCA(var1,var2):
    ### Read in data of 2 variables
    print(type(events))
    v1 = variables[var1]
    print(v1, type(v1))
    v2 = variables[var2]
    print(v2, type(v2))
    m1 = events.array(v1)
    m2 = events.array(v2)
    print(m1, m2, type(m1), type(m2), m1.shape, m2.shape, sep="\n")
    matrix          = m1.flatten()
    matrix          = np.vstack((matrix, m2.flatten()))
    matrix          = matrix.T
    pca = PCA(n_components=2)
    pca.fit(matrix)
    """
    print("Working with correlation: ",variables[var1],variables[var2])
    print("PCA Eigenvalues: ")
    print(pca.explained_variance_)
    print(" ")
    print("PCA Components/vectors: ")
    print(pca.components_)
    """

    return pca.explained_variance_,pca.components_

for i in range(0,len(variables)):
#for i in range(0,1):
    for j in range(0,len(variables)):
    #for j in range(0,1):
        temp = calculatePCA(i,j)
        eigen[i][j][0],eigen[i][j][1]   = temp[0][0],temp[0][1]
        vector[i][j][0],vector[i][j][1] = temp[1][0][0],temp[1][0][1]
        vector[i][j][2],vector[i][j][3] = temp[1][1][0],temp[1][1][1]

np.save("numpy/"+name+"eigen",eigen)
np.save("numpy/"+name+"vector",vector)

<class 'uproot.rootio.TTree'>
b'eventWeight' <class 'bytes'>
b'eventWeight' <class 'bytes'>
[[1.0 1.0] [1.0 1.0] [1.0 1.0] ... [1.0 1.0] [1.0 1.0] [1.0 1.0]]
[[1.0 1.0] [1.0 1.0] [1.0 1.0] ... [1.0 1.0] [1.0 1.0] [1.0 1.0]]
<class 'awkward.array.jagged.JaggedArray'>
<class 'awkward.array.jagged.JaggedArray'>
(5000,)
(5000,)
<class 'uproot.rootio.TTree'>
b'eventWeight' <class 'bytes'>
b'sigJetPt' <class 'bytes'>
[[1.0 1.0] [1.0 1.0] [1.0 1.0] ... [1.0 1.0] [1.0 1.0] [1.0 1.0]]
[[166.25909442881849 118.90896772514594 15.531610870264318] [128.42377435866584 102.86987676666519 48.14748595127195 15.6486237714586] [127.104102400976 84.65878858050905 57.247802081078866] ... [185.19624724753413 160.7717412319058 136.0618722803899 ... 56.07885582619968 48.750093987606405 34.31370818258431] [158.06970582564713 92.52032240638702 39.264967209946626 20.209149213532328 13.59656984461042] [123.10873777791134 120.14533806220528]]
<class 'awkward.array.jagged.JaggedArray'>
<class 'awkward.array.jagged.

/cvmfs/alice.cern.ch/el7-x86_64/Packages/Python-modules/1.0-260/share/python-modules/lib/python/site-packages/sklearn/decomposition/pca.py:446: RuntimeWarning: invalid value encountered in true_divide
  explained_variance_ratio_ = explained_variance_ / total_var


ValueError: all the input array dimensions except for the concatenation axis must match exactly